### ISSUE TITLE
Please let lookup by common name

### ISSUE THREAD

**Issue by hongquan** [Atem18/isocodes#20]
Example:

```py
>>> from isocodes import countries
>>> countries.get(alpha_2='VE')
{'alpha_2': 'VE', 'alpha_3': 'VEN', 'common_name': 'Venezuela', 'flag': '🇻🇪', 'name': 'Venezuela, Bolivarian Republic of', 'numeric': '862', 'official_name': 'Bolivarian Republic of Venezuela'}

>>> countries.get(common_name='Venezuela')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/quan/Works/Envs/vieperid/lib/python3.10/site-packages/isocodes/__init__.py", line 30, in get
    return [element for element in self.data if element[key] == kwargs[key]][0]
  File "/home/quan/Works/Envs/vieperid/lib/python3.10/site-packages/isocodes/__init__.py", line 30, in <listcomp>
    return [element for element in self.data if element[key] == kwargs[key]][0]
KeyError: 'common_name'

'common_name'
```

**Comment by Atem18** [comment]
Hi @hongquan,

Thanks for the bug report. It's now fixed in the version 2022.8.2.
