### ISSUE TITLE
Use importlib.resources for python >=3.9

### ISSUE THREAD

**Issue by lordwelch** [Atem18/isocodes#281]
Currently isocodes does not work with PyInstaller 6.2.0.
importlib.resources is available for Python >=3.9 for Python 3.8 isocodes can either depend on the importlib_metadata>=1.3 backport package or fall back to __file__ which does work with PyInstaller.
Using importlib.resources would also make isocodes compatible with more exotic python loaders with minimal effort https://pyoxidizer.readthedocs.io/en/v0.6.0/packaging_pitfalls.html (yes pyoxidizer is on 0.23.0 and now supports the `__file__` attribute for loading filesystem resources, but the information is still valid, later documentation splits it up into several different pages)

I can open a pull request if you would like

An example of how this could be implemented:
```python
def get_resource(resource: str) -> 'importlib.resources.abc.Traversable':
    """Return a file handle on a named resource in a Package."""

    # Attempt impotlib.resources
    if sys.version_info >= (3, 9):
        import importlib.resources
        return importlib.resources.files('isocodes').joinpath(resource)

    # Attempt importlib_resources backport
    try:
        if sys.version_info < (3, 9):
            import importlib_resources
            return importlib_resources.files('isocodes').joinpath(resource)
    except ImportError:
        ...

    # Fall back to __file__.

    # Undefined __file__ will raise NameError on variable access.
    try:
        package_path = os.path.abspath(os.path.dirname(__file__))
    except NameError:
        package_path = None

    if package_path is not None:
        resource_path = os.path.join(package_path, resource)

        return pathlib.Path(resource_path)

    # Could not resolve package path from __file__.
    raise Exception(f'do not know how to load resource: {resource}')


class ISO:
    iso_key: str
    data: List[Dict[str, str]]

    def __init__(self, iso_key: str) -> None:
        self.iso_key = iso_key
        with get_resource(
            f"share/iso-codes/json/iso_{self.iso_key}.json"
        ).open(encoding="utf-8") as iso_file:
            self.data = json.load(iso_file)[self.iso_key]
```

Here is a reproducible example

```console
$ pyinstaller main.py --collect-data isocodes
$ dist/main/main
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import isocodes
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "isocodes/__init__.py", line 317, in <module>
  File "isocodes/__init__.py", line 92, in __init__
FileNotFoundError: [Errno 2] No such file or directory: '/home/lordwelch/isocodes/dist/main/share/iso-codes/json/iso_3166-1.json'
[28509] Failed to execute script 'main' due to unhandled exception!
```

main.py:
```python
import isocodes
print('success')
```

**Comment by Atem18** [comment]
@lordwelch Hi, thanks for the bug report.

You can go ahead and open a PR. If you can even implement tests to test the pyinstaller integration, that would be even better.
